# ansible/roles/postgresql/tasks/databases_manager.yml
---
  - name: "Postgresql: Managing databases"
    postgresql_db:
      name: "{{ item.name }}"
      owner: "{{ item.owner }}"
      port: "{{ item.port | default(postgresql_port_number)}}"
      state: "{{ item.state }}"
      login_user: "{{ postgresql_default_owner }}"
      login_password: "{{ vault_postgresql_password }}"
    with_items:
      - "{{ postgresql_databases }}"
    when: postgresql_databases is defined
