# ansible/roles/postgresql/tasks/extensions_manager.yml
---
  - name: "Postgresql: Managing databases extensions"
    postgresql_ext:
      db: "{{ extension_item.0.name }}"
      name: "{{ extension_item.1.name }}"
      port: "{{ extension_item.0.port | default(postgresql_port_number) }}"
      state: "{{ extension_item.1.state }}"
      login_user: "{{ postgresql_default_owner }}"
      login_password: "{{ vault_postgresql_password }}"
    with_subelements:
      - "{{ postgresql_databases }}"
      - extensions
    loop_control:
      loop_var: extension_item
    when: postgresql_databases is defined
