# ansible/roles/postgresql/tasks/main.yml
---
  - import_tasks: prerequisites.yml
  - import_tasks: pg_pass_manager.yml
    when: pg_pass is defined
  - import_tasks: hba_manager.yml
    when: postgresql_hba_entries is defined
  - import_tasks: roles_manager.yml
    when: postgresql_roles is defined
  - import_tasks: databases_manager.yml
    when: postgresql_databases is defined
  - import_tasks: extensions_manager.yml
    when: postgresql_databases is defined
  - import_tasks: privileges_manager.yml
    when: postgresql_privileges is defined
