# roles/postgresql/tasks/privileges.yml
---
- name: "Postgresql: managing roles privileges"
  postgresql_privs:
    database: "{{ item.database }}"
    roles: "{{ item.roles }}"
    objs: "{{ item.objs | default(omit)}}"
    type: "{{ item.type }}"
    privs: "{{ item.privs | default(omit)}}"
    schema: "{{ item.schema | default(omit)}}"
    login_user: "{{ postgresql_default_owner }}"
    login_password: "{{ vault_postgresql_password }}"
  with_items:
    - "{{ postgresql_privileges }}"
  when: postgresql_privileges is defined
