---
vpc_cidr_block: 10.{{ vpc_network }}.0.0/16
vpc_dns_support: "true"
vpc_dns_hostnames: "true"
vpc_tenancy: "default"
vpc_tags:
  - key: "Name"
    value: "{{ global_name }}-vpc"
  - key: "CatProject"
    value: "{{ global_name }}-Network"
  - key: "Env"
    value: "{{ global_name }}"
igw_tags:
  - key: "Name"
    value: "{{ global_name }}-ig"
  - key: "CatProject"
    value: "{{ global_name }}-Network"
  - key: "Env"
    value: "{{ global_name }}"


# a map defining the subnets we will build in the VPC
vpc_subnets:
  - name: "test"
    cidr: "10.{{ vpc_network }}.0.0/24"
    az: "{{ aws_region }}a"
    map_public: "yes"
  - name: "test"
    cidr: "10.{{ vpc_network }}.1.0/24"
    az: "{{ aws_region }}a"
    map_public: "yes"
  - name: "test"
    cidr: "10.{{ vpc_network }}.2.0/24"
    az: "{{ aws_region }}b"

# a list defining the security groups for our VPC
vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        from_port: 0
        to_port: 65535
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443
