# ansible/roles/redis/tasks/install_manager.yml
---
   - name: install redis-server
     package:
       name: redis-server
       state: present
   
#KERNEL CONFIGURATION
  - name: vm swappiness > 0
    sysctl:
      name: vm.swappiness
      value: 0
      sysctl_set: yes
      state: present
  - name: vm overcommit memory > 1
    sysctl:
      name: vm.overcommit_memory
      value: 1
      sysctl_set: yes
      state: present
  - name: somaxconn 65535
    sysctl:
      name: net.core.somaxconn
      value: 65535
      sysctl_set: yes
      state: present
  - name: Copying init script
    copy:
      src: disable-transparent-hugepages
      dest: /etc/init.d/disable-transparent-hugepages
      owner: root
      group: root
      mode: 0755
  - name: enable sysv disable-transparent-hugepages service
    service: name=disable-transparent-hugepages enabled=yes
  - name: start disable-transparent-hugepages
    service: name=disable-transparent-hugepages state=started
  - name: Redis bind IP
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^bind'
      line: 'bind 0.0.0.0'
      backup: yes
  - name: Redis database number
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^databases'
      line: 'databases 500'
  - name: Redis Master Password
    replace:
      path: /etc/redis/redis.conf
      regexp: '# masterauth <master-password>'
      replace: requirepass {{ requirepass }}
  - name: Redis defining RequirePass
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: '^requirepass'
      line: requirepass {{ requirepass }}
    notify: "Redis_restarted"
