# ansible/roles/mongodb/tasks/install_manager.yml
---
  - name: "Adding mongodb key"
    apt_key:
      keyserver: "{{ mongodb_repository_signing_key_url }}"
      id: "{{ mongodb_repository_signing_key }}"

  - name: "Adding mongodb repo"
    apt_repository:
      filename: "{{ mongodb_debian_stretch_repository }}"
      repo: "{{ mongodb_debian_repository }}"
      state: "present"
    when: ansible_distribution  == "debian"

  # apt-get update lancé par le module apt_repository précédent
  - name: "Install mongodb packages"
    apt:
      name: "{{ mongodb_packages }}"

  - name: "Changing 127.0.0.0 to 0.0.0.0 in {{ mongodb_conf_file }}"
    replace:
      path: "{{ mongodb_conf_file }}"
      regexp: '127\.0\.0\.1'
      replace: '0.0.0.0'

  - name: "Restarting mongod service"
    service:
      name: "mongod"
      state: "restarted"
