# ansible/roles/apache/tasks/opcache_manager.yml
---
  - import_tasks: apache_scripts_manager.yml
  
  - name: Create opcache folder for Apache
    file:
      path: "{{ item.path }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      state: "{{ item.state }}"
      mode: "{{ item.mode }}"
    with_items:
      - "{{ opcache_folders }}"
    
  - name: Customize hosts
    lineinfile:
      path: /etc/hosts
      insertbefore: EOF
      regexp: '{{ item.name }}'
      line: "127.0.0.1 {{ item.name }}"
      state: present
    with_items:
      - "{{ opcache_vhosts }}"
    
  - name: Add Custom hosts entry Opcache
    lineinfile:
      path: "/etc/hosts"
      insertafter: "#CUSTOM HCD"
      regexp: "{{ item.name }}"
      line: "127.0.0.1 {{ item.name }}"
      state: present
    with_items:
      - "{{ opcache_vhosts }}"
      
  - name: Copying Opcache php file
    copy:
      src: create-vhost/SOURCES/check_opcache.php
      dest: /usr/lib/nagios/www/check_opcache.php
      owner: www-data
      group: www-data
      mode: 0755
      
  - name: Create Apache vhosts
    shell: |
      chmod +x /opt/create-vhost/*.sh
      /opt/create-vhost/index-opcache.sh > /tmp/create-vhost.log
      
  - name: Clean files
    shell: rm -rf /opt/create-vhost
  - name: Create Logrotate Configuration
    shell: cp -Ra /etc/logrotate.d/apache2 /etc/logrotate.d/apache2-opcache
  - name: Customize Logrotate Configuration
    replace:
      path: /etc/logrotate.d/apache2-opcache
      regexp: '/var/log/apache2/'
      replace: /usr/lib/nagios/www//log/
  
  