---
- name: Configuration de la sauvegarde barman sur le serveur de bases de données postgresql
  hosts: "{{ inventory_host_name }}"
  
  vars_prompt:
    - name: "postgres_server_name"
      prompt: "Nom du serveur postgresql"
      default: "S5LXPGBCKHCD01"
      private: no
  vars:
    current_barman_server_configuration:
      - name: "{{ postgres_server_name }}"
            
  tasks:
    - name: Exécution de la configuration barman
      include_role:
        name: barman
        tasks_from: create_slot
      vars:
        barman_server_configuration: "{{ current_barman_server_configuration }}"
