# deploy_databases.yml
---
- hosts: database
  become: yes
  tasks:
    - name: Exécution du rôle postgresql
      include_role:
        name: postgresql-{{ pg_version }}
    - name: Exécution du rôle debian
      include_role:
        name: debian
