# ansible/deploy_virtual_machines_wrapper.yml
---
- hosts: "{{ inventory_hostname }}"
  vars_prompt:
    - name: "database_name"
      prompt: "Nom de la base de données à créer"
      private: no
  tasks:
    - debug:
        msg: play1

- name: "Ajout des utilisateurs"
  import_playbook: deploy_debian_users.yml

- name: "Configuration du mysecureshell"
  import_playbook: deploy_mysecureshell.yml
