---
- name: Configuration sources.list
  hosts: "{{ inventory_hostname }}"
  become: yes

    tasks:
      # WHEEZY
      - name: "Adding wheezy repo"
        apt_repository:
          filename: "/etc/apt/sources.list"
          repo:
          state: "present"
        with_items:
          - "deb http://archive.debian.org/debian/ wheezy contrib main non-free"
          - "deb-src http://archive.debian.org/debian/ wheezy contrib main non-free"
          - "deb http://archive.debian.org/debian wheezy-backports main contrib non-free"
          - "deb-src http://archive.debian.org/debian wheezy-backports main contrib non-free"
        when: ansible_distribution_release == "wheezy"
      - name: "Adding jessie Repo"
        apt_repository:
          filename: "/etc/apt/sources.list"
          repo:
          state: "present"
        with_items:
          - "deb http://deb.debian.org/debian jessie  contrib main non-free"
          - "deb-src http://deb.debian.org/debian debian jessie contrib main non-free"
          - "deb http://security.debian.org/ jessie/updates main contrib non-free"
          - "deb-src http://security.debian.org/ jessie/updates main contrib non-free"
          - "deb http://deb.debian.org/debian jessie-backports main contrib non-free"
          - "deb-src http://deb.debian.org/debian jessie-backports main"
        when: ansible_distribution_release == "jessie"
      - name: "Adding stretch Repo"
        apt_repository:
          filename: "/etc/apt/sources.list"
          repo:
          state: "present"
        with_items:
          - "deb http://httpredir.debian.org/debian stretch  contrib main non-free"
          - "deb-src http://httpredir.debian.org/debian stretch contrib main non-free"
          - "deb http://security.debian.org/ stretch/updates main contrib non-free"
          - "deb-src http://security.debian.org/ stretch/updates main contrib non-free"
          - "deb http://deb.debian.org/debian stretch-backports main contrib non-free"
          - "deb-src http://deb.debian.org/debian stretch-backports main"
        when: ansible_distribution_release == "stretch"
      - name: "Adding stretch Repo"
        apt_repository:
          filename: "/etc/apt/sources.list"
          repo:
          state: "present"
        with_items:
          - "deb http://httpredir.debian.org/debian buster  contrib main non-free"
          - "deb-src http://httpredir.debian.org/debian buster contrib main non-free"
          - "deb http://security.debian.org/ buster/updates main contrib non-free"
          - "deb-src http://security.debian.org/ buster/updates main contrib non-free"
          - "deb http://deb.debian.org/debian buster-backports main contrib non-free"
          - "deb-src http://deb.debian.org/debian buster-backports main"
        when: ansible_distribution_release == "buster"
