# ansible/roles/ldap2pg/tasks/RedHat/main.yml
---
  - name: "Adding dalibo labs key"
    ansible.builtin.yum:
      name: 'https://yum.dalibo.org/labs/dalibo-labs-4-1.noarch.rpm'
      state: present
      disable_gpg_check: true
      