# ansible/inventories/dalibo/production/host_vars/localhost/vars.yml
---
  dalibo_packages:
    - "pidgin"
    - "libreoffice"
    - "thunderbird"
    - "docker.io"
    - "simplescreenrecorder"
    - "vokoscreen"
    - "simple-scan"
    - "google-chrome-stable"
    - "terminator"
    - "remmina"
    - "git"
    - "typora"
    - "qemu-kvm"
    - "virt-manager"
    - "pdfsam"
    - "okular"
    - "curl"
    - "make"
    - "openrazer-meta"
    - "pulseaudio"
    - "pulseaudio-utils"
    - "pulseaudio-module-bluetooth"
    - "pgmodeler"
    - "python3-django"
    - "gettext"

  dalibo_snaps:
    - name: "atom"
      classic: "yes"
    - name: "dbeaver-ce"
    - name: "brave"
