# ansible/roles/vmware/tasks/custom_manager.yml
---
  # get date
  - name: "Getting date"
    set_fact: creationdate="{{lookup('pipe','date "+%d/%m/%Y %H:%M"')}}"

  - name: "Updating LVM"
    shell: sudo pvresize /dev/sdb

  # Paramétrage IP
  - name: "Setting IP"
    shell: sudo sed -i 's/10.180.10.253/'{{ vsphere_ip }}'/g' /etc/network/interfaces

  # Paramétrage Firewall
  - name: "Setting Firewall"
    shell: sudo sed -i 's/172.20.66.253/'{{ vsphere_ip }}'/g' /etc/default/minifirewall

  # Paramétrage Hosts
  - name: "Setting hosts"
    shell: sudo sed -i 's/192.168.15.165/'{{ vsphere_ip }}'/g' /etc/hosts
    
  - name: "Setting hosts"
    shell: sudo sed -i 's/s0lxjessieTDF01/'{{ inventory_hostname }}'/g' /etc/hosts

  # Paramétrage Hostname
  - name: "Setting hostname"
    shell: sudo sed -i 's/s0lxjessieTDF01/'{{ inventory_hostname }}'/g' /etc/hostname

  # Paramétrage Postfix
  - name: "Setting postfix"
    shell: sudo sed -i 's/s0lxjessieTDF01/'{{ inventory_hostname }}'/g' /etc/postfix/main.cf
    
  - name: "Setting postfix"
    shell: sudo chmod 644 /etc/postfix/main.cf

    # Paramétrage hostname resolv
  - name: "Setting hostname resolv"
    shell: sudo sed -i 's/10.160.40.1/10.180.40.1/g' /etc/resolv.conf
  - name: "Setting hostname resolv"
    shell: sudo sed -i 's/nameserver 192.168.60.210/''/g' /etc/resolv.conf
    notify: "Restart server"


  - name: waiting 30 secs for server to come back
    local_action: wait_for host={{ vsphere_ip }} port=22 state=started delay=30 timeout=60
