# ansible/roles/vmware/tasks/guests_manager.yml
---
  - name: "debugging"
    debug:
      var: vmware_guests
  - name: "Managing the VM"
    vmware_guest:
      hostname: "{{ item.hostname }}"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      validate_certs: "no"
      esxi_hostname: "{{ item.esxi_hostname }}"
      datacenter: "{{ item.datacenter }}"
      folder: "{{ item.folder }}"
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      guest_id: "{{ item.guest_id }}"
      annotation: "{{ item.annotation }}"
      disk: "{{ item.disks }}"
      hardware: "{{ item.hardware}}"
      template: "{{ item.template }}"
      wait_for_ip_address: "yes"
    with_items:
      - "{{ vmware_guests }}"