# ansible/roles/git/tasks/config_manager.yml
---
  - name: "Configuration global user name"
    shell: sudo su {{ git_user_configs_item.user }} -c "git config --global user.name '{{ git_user_configs_item.global_user_name }}'"
    with_items:
      - "{{ git_user_configs }}"
    loop_control:
      loop_var: git_user_configs_item

  - name: "Configuration global email"
    shell: sudo su {{ git_user_configs_item.user }} -c "git config --global user.email '{{ git_user_configs_item.global_email }}'"
    with_items:
      - "{{ git_user_configs }}"
    loop_control:
      loop_var: git_user_configs_item
