# ansible/roles/git/tasks/pull_manager.yml
---
  - name: "Pulling"
    git:
      repo: "git@gitlab.devdata.fr:SYS/ansible.git"
      dest: "/tmp/ansible"
      update: yes
      version: master
    
    