# ansible/roles/postgresql/tasks/hba_manager.yml
---
  - name: Configure host based authentication (if entries are configured).
    template:
      src: "pgbouncer_hba.conf.j2"
      dest: "{{ pgbouncer_auth_hba_file }}"
      owner: "{{ pgbouncer_sys_user }}"
      group: "{{ pgbouncer_sys_group }}"
      mode: 0600
    when: pgbouncer_hba_entries is defined

  - name: "reload pgbouncer"
    service:
      name: "pgbouncer"
      state: "reloaded"
