# ansible/roles/mysecureshell/tasks/install_manager.yml
---
  - name: "Install mysecureshell packages"
    apt:
      name: "{{ mysecureshell_packages }}"
- name: install mysecureshell
  package:
    name: mysecureshell
    state: present
- name: Customize Home directory
  replace:
    path: /etc/ssh/sftp_config
    regexp: '/home/$USER'
    replace: '$HOME'
- name: Customize GlobalDownload
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'GlobalDownload          50k'
    replace: 'GlobalDownload          5000k'
- name: Customize Download
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'Download                5k'
    replace: 'Download                5000k'
- name: Customize LimitConnection
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'LimitConnection         10'
    replace: 'LimitConnection         50'
- name: Customize LimitConnectionByUser
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'LimitConnectionByIP     2'
    replace: 'LimitConnectionByIP     50'
- name: Customize DefaultRights
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'DefaultRights           0640 0750'
    replace: 'DefaultRights           0660 0770'
- name: Customize LimitConnectionByIP
  replace:
    path: /etc/ssh/sftp_config
    regexp: 'LimitConnectionByUser   50'
    replace: 'Download                5000k'
