---

- name: "Ajoute les clé apt"
  ansible.builtin.apt_key:
    url: "{{ current_dalibo_apt_key.url }}"
    state: "{{ current_dalibo_apt_key.state | default('present') }}"
  with_items: "{{ dalibo_apt_keys }}"
  loop_control:
    loop_var: "current_dalibo_apt_key"

- name: "Ajoute les dépôts"
  ansible.builtin.apt_repository:
    repo: "{{ current_dalibo_apt_repository.repo }}"
    state: "{{ current_dalibo_apt_repository.state | default('present') }}"
    filename: "{{ current_dalibo_apt_repository.filename }}"
  with_items: "{{ dalibo_apt_repositories }}"
  loop_control:
    loop_var: "current_dalibo_apt_repository"

- name: "Installe les packages par défauts"
  ansible.builtin.apt:
    name: "{{ dalibo_packages }}"
    state: "latest"

- name: "Ajoute les snaps"
  community.general.snap:
    name: "{{ current_dalibo_snap.name }}"
    classic: "{{ current_dalibo_snap.classic | default('no') }}"
  with_items: "{{ dalibo_snaps }}"
  loop_control:
      loop_var: "current_dalibo_snap"

# Attention le home peut varier
- name: "Génère une clef SSH pour l'utilisateur {{ username }}"
  openssh_keypair:
    path: "/home/{{ username }}/.ssh/id_rsa"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src:  "{{ current_dalibo_template.src }}"
    dest: "{{ current_dalibo_template.dest }}"
    owner: "{{ current_dalibo_template.owner }}"
    group: "{{ current_dalibo_template.group }}"
    mode: "{{ current_dalibo_template.mode }}"
  with_items: "{{ dalibo_templates }}"
  loop_control:
      loop_var: "current_dalibo_template"
