---
  - name: "{{ file_path }} : remplace la regexp {{ parameter_regexp }} par {{ parameter_value }}"
    lineinfile:
      path: "{{ file_path }}"
      regexp: "{{ parameter_regexp }}"
      line: "{{ parameter_value }}"
      state: present